# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04f98e8487661781106344250ccb838f1faddc8fb4244c55133696c5d800e8a1116d1f04b86d9fd7fd04cdb9309de8827320603423113bbf0f4b9f4ed8a05ddf

test:
  secret_key_base: 84556eda7d187ac0da2862be38a3d0eb6c542c9b0e971ce9d01e86d48ec10b4f9808250c4610494818e956f47bcc88c6c74804d69fb18a7e0f6e884849b3ff1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
