# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69e47fa24ec68a37834af9e236c4f4f1ae5529d7837d3f99a9afc17d4fda54c2bc423214d004a22e9d386d3b5a0d99d7bf4ce742cacbeacf28273b222679299b

test:
  secret_key_base: 0031e5b40b47083e1c76389687364f77b749056a01609bdc1ff7033b342d2c04ec5f64719d782fc2ff3545c94dc4e82d34e83cd8a63864e1c4e1c42850848ed6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
