# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5739cd159bed5914fada3977dfffcb55db51989cb4d1d7dda975cc787821786c78173bc51fdf008e9f753b42036575a27a5878f99c8e20227a3d5cf588cd4f03

test:
  secret_key_base: 82dce93b900095d7203ae57ddf1b26b27ebb73fbee80ee82f4fa59338894fb6fc31a6d638dce12d88fc9c2a1a9a0f422759c0ceb77e0911e0c84ac7c6de75a3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
