# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac654d5423aea00999c65e75d697e06ef5897df134125661cf65e78a7e576251552e4911c289c5d5f0767027bd46d81cb48319e1ce9e8dd223849c32ed9b906a

test:
  secret_key_base: bc23f10e438bd4203d647512300eafe7ba161830034058afb21d2ff5303cc18d28e7ca0bdbd5637793429527853b7d57976e07ea2a9cb9af1f87490006b7bc41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
