# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5c39701609ec5e6fef93d8b97a6cda490ad807c2afb8138c4ef53b9742c91cdc3cd3ab1c292d8806e84f206bb43aaf6f72ab99b79f2b0b1f594c43e59964981

test:
  secret_key_base: 5fd2da7592383123922255db20b3fa79911b015422c332b497a4ba118cb2655e91e072c6b7ac706d230e38fe813263e0d3573633a4a4052cd3abb59f9f0073bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
