# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25843f40af212925611b8aec9b4ecdae07b794b41ff5f49f0187f1eaabc2548945e117f050a6333d8561def4a52c1932191157ce1f0db0b40cd8d11a37336011

test:
  secret_key_base: ffc72edb9fd7af2e45be6e1f9af6ab5f3b3a99ecb5943dfb38c2972cb7013cfc936f2ec96e5be629e0a939b03fc957eeb3b9712d9d7e9db703e7db027cc3a9eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
