# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2d0989bc33cced4b0ebf3c4ccdf37cde2d6a82cded682c26bd3e15c4a41cb27b5e3023d1be9d1c8488342b365492bb2c481622d5554df2396b32fb4f9026025

test:
  secret_key_base: 91a1d9e07537bc635ccc29d2e270ef615761e50af69f599135bbc0c8b913a5967b81633539b6398dfd2c501cb2a03132914e64e0f664d45189f0edf4b145b191

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
